### ISSUE TITLE
A.R.T not visible on site.

### ISSUE THREAD

**Issue by paawankataria** [mattfeldman/discordlist#15]
i created Art-and-Culture in discordlist/_data/nav.yml and Art-and-Culture/A.R.T.md in _links/Other/ and it still not visible on site. idk what to do now :(

**Comment by diomed** [comment]
Could it be because you named folder Art-and-Culture instead of Art and Culture?
Every other folder folder is named without dashed, and yours has one. 

Anyway, Matt's gonna kill me for merging this, but I thought lets give it a try, since he's not around so much. I usually only delete expired channels.

**Comment by paawankataria** [comment]
well it is Art-and-Culture on folder as well as nav.yml and my Channel is not expired .

**Comment by diomed** [comment]
what I'm trying to tell you, is that it should probably be without dashes.
And that I'm only co-admin here, who approved it as it was.

expiration of channels is only mentioned, and has nothing to do with you.

**Comment by paawankataria** [comment]
ok i retry creating it but it's not showing art and culture without "-"

**Comment by paawankataria** [comment]
ok i added and merged but please delete those with "-" and when it will be updated on site ?

it did showed "Art and Culture" but not my discord link. is it bcoz i added a new class my self and i need to add it somewhere else ?

**Comment by diomed** [comment]
Here, I've fixed it, finally :smiley: 
So, there's a lesson to be learned here, and that is : tags **are not arbitrary here**.
See the code of how it's supposed to be to display here.

**Comment by paawankataria** [comment]
ok got it . thank you so much. :D but in nav.yml there are 2 "-Art and Culture" .
